- lib/controllers.js
Hi,
This is an optimisation for serving the home page of a static site. Stops the whole bucket contents being read and parsed.
thanks,
David
> Optimise the loading of the home page (root)

- lib/file-store.js
- lib/xml-template-builder.js
- test/test.js
Fixes issue #10 
This expands the previous support for using Delimiters and also includes the CommonPrefixes data that is supposed to be returned by the server.
> CommonPrefixes support

- lib/file-store.js
- lib/xml-template-builder.js
- test/test.js
> Added support for delimiter option when listing objects.

- lib/xml-template-builder.js
> fixing issue #15 - support AmazonS3Client.listObjects by fixing wrong XML element

- lib/app.js
- lib/controllers.js
- lib/file-store.js
- package.json
This might be an easy fix, but I don't have much experience messing around with the boilerplate of an Express app to get large media files served correctly.
Actual S3 response:
I'll be looking into this and will submit a pull request if I figure something out.
> Audio/Video files not served properly - unable to scrub with HTML5 player

- lib/index.js
- test/test.js
Default options replaced by options passed to S3rver
Default options merge with options passed to S3rver
> S3rver options merge fix

- lib/xml-template-builder.js
Changed Error Message for 'NoSuchBucket' to 'The specified bucket does not exist'
> Fixe for #51: Incorrect Error Message

- lib/controllers.js
- lib/file-store.js
Just realized I've been holding on to these changes for a while now, I guess I hadn't realized I wasn't using your npm packages.
> Preserve Content-Disposition in copyObject, fix If-None-Match header

- .travis.yml
- README.md
- lib/app.js
- lib/controllers.js
- test/test.js
cc: @leontastic
~~Some tests are failing. I am going to fix them.~~
Ready for merge ☺️
> ci(node): Update runtime versions

- test/test.js
> test(listObjects): Adds test for issue #60

- package.json
- test/test.js
Some builds are failing due to timeout: https://travis-ci.org/jamhall/s3rver/builds/332666208
I increased the timeout to 30 seconds.
> Increase test timeout globally

- test/test.js
> Cleanup winston instance. Fixes #101

- bin/s3rver.js
- lib/app.js
- lib/controllers.js
- lib/file-store.js
- lib/index.js
- lib/logger.js
- lib/models/bucket.js
- lib/models/s3-object.js
- lib/utils.js
- lib/xml-template-builder.js
- test/test.js
> Change var to const/let

- lib/utils.js
- test/test.js
Updated removeEmptyDirectories so that the top level directory passed is not deleted itself.
> Fix issue where deleting the last top level object also deletes the bucket

- package.json
**Draft release notes:**
Fixes:
- Support running on port 0 #163
- Fix issue where deleting the last top level object also deletes the bucket #166 
- Fix script globs #170
- Cleanup and fixes #156
- Update dependencies #151 #152 #157 #158 #159 #160 #161 #164 #165 #167 #169
> Increment version to v2.2.1

- package.json
- test/test.js
I accidentally pushed to master initially 😬, sorry about that.
Anyway this is for #155 since extending the Object prototype isn't that great.
> refactor(test): Use chai-expect instead of should

- lib/controllers.js
- lib/xml-template-builder.js
- test/test.js
This fixes another regression with the last patch.
Fixes #185
> Include bucket name in listObjects XML response

- lib/controllers.js
- lib/models/s3-event.js
- test/test.js
This should hopefully be the last of the regressions that got introduced with the last patch!
> Size and MD5 missing in certain event types

- README.md
https://github.com/jamhall/s3rver/issues/428
> Fix documentation (Issue #428)

- lib/routes.js
Partially addresses #436. Actual implementation will hopefully come in the next minor release.
> Stub Upload Part - Copy endpoint with 501

- lib/middleware/authentication.js
> Correct header name: date, not Date

- README.md
- lib/s3rver.js
> expose S3rver#configureBuckets for preconfiguring buckets programmatically

- README.md
- bin/s3rver.js
- lib/middleware/authentication.js
- lib/middleware/cors.js
- lib/middleware/vhost.js
- lib/middleware/website.js
- lib/routes.js
- lib/s3rver.js
- package.json
- test/test.js
> Fix v2 signature checking when mounting S3rver with baseUrl

- lib/models/error.js
- lib/s3rver.js
- package.json
Closes #497 (supersedes #496).
> Workaround for breaking change in fast-xml-parser

- lib/controllers/bucket.js
- lib/controllers/object.js
- lib/models/config.js
- lib/routes.js
- lib/stores/filesystem.js
- lib/utils.js
- test/test.js
Still a work-in-progress.
Adds Object Tagging support. PutObjectTagging saves a `key.tagging.xml` subresource in the data directory containing the tags, and GetObjectTagging reads that file.
> Object Tagging support

- lib/middleware/website.js
- test/test.js
Fixes #502
All the tests pass, and I've also tested it locally with my web app.
> Detect SDK/CLI usage with x-amz-* headers and query string parameters

- lib/controllers/bucket.js
- lib/routes.js
- test/controllers/bucket.spec.js
> Add bucket location

- README.md
> Fixing vhostBuckets documentation

- README.md
- lib/controllers/bucket.js
- lib/controllers/object.js
- lib/controllers/service.js
- lib/middleware/authentication.js
- lib/middleware/cors.js
- lib/middleware/logger.js
- lib/middleware/website.js
- lib/models/config.js
- lib/models/error.js
- lib/models/event.js
- lib/routes.js
- lib/s3rver.js
- lib/stores/filesystem.js
- lib/utils.js
- test/controllers/bucket.spec.js
- test/controllers/object.spec.js
- test/controllers/service.spec.js
- test/helpers.js
- test/middleware/authentication.spec.js
- test/middleware/cors.spec.js
- test/middleware/vhost.spec.js
- test/middleware/website.spec.js
- test/s3rver.spec.js
- test/setup.js
This PR is the result of running `npm run prettier -- --write` after merging #606
Might need to test this against upgraded eslint dependencies too
> Prettier v2 formatting changes

- lib/models/object.js
- lib/stores/filesystem.js
- lib/utils.js
- test/controllers/bucket.spec.js
- test/controllers/object.spec.js
- test/helpers.js
- test/middleware/authentication.spec.js
- test/middleware/cors.spec.js
- test/middleware/website.spec.js
- test/s3rver.spec.js
Reimplementation of #639 now that Node v10 is EOL.
> refactor(deps): drop fs-extra as dependency

- lib/stores/filesystem.js
I have notice some code duplicated, so I suggest extract helper method in store for that.
> Remove duplicate code for save content in store
