- lib/app.js
In order to support cleanly shutting down the express app after calling `run`, the result of calling express's `listen` method must be returned. This adds support for:
```javascript
var server = s3rver
.setHostname('localhost')
.setPort(4568)
.setDirectory(S3_DIR)
.setSilent(true)
.run(function (err, host, port) {
});
server.close(function(err) {
});
```
This is a pretty essential feature during testing.
> Expose HTTP server to support calling `close`

- lib/file-store.js
This is a fix for issue #6.
On the Windows OS, file paths use the backslash to delimit each folder while object keys expect the forward slash. When walking file storage items, we explicitly convert the slashes so they match our expected `object key` format.
I have run this change through this projects unit tests as well as my own and they all pass now.
> listObjects compatibility with Windows OS

- lib/controllers.js
- lib/xml-template-builder.js
- test/test.js
The ETag should be surrounded by double quotes.
Some client libraries such as boto require this format and refuse GET requests otherwise:
`IOError: Cannot store S3 object "bucket/object": ETag from S3 did not match computed MD5. 34913be17f33fe36466f5b932aff626f vs. 34913be17f33fe36466f5b932aff626f`
RFC: https://tools.ietf.org/html/rfc7232#section-2.3
Amazon also lists quoted ETags in examples in their documentation:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html
There were quite a few occurrences in the code - hopefully I found all of them. The tests are passing and boto works as expected.
> Fix ETag field format in HTTP response

- bin/s3rver.js
- lib/app.js
This is a simple solution to allow all CORS requests, which are necessary when using s3rver for testing web applications. I tested it with Chromium.
> Allow CORS Requests

- lib/app.js
- lib/controllers.js
- lib/file-store.js
- lib/index.js
HI 
With these changes we can use any file system to be used as backend for s3rver .
Currently s3rver uses fs-extra as a file system for this server .  if a user has a file system which exposes functions with same semantics and signatures as that of fs file system but works under different environment or protocols  then we can use that in place of fs or fs extra
> Allows users to plug in other file systems providers instead of fs-extra only 

- lib/controllers.js
Fixes https://github.com/jamhall/s3rver/issues/30
Since S3's documentation is ambiguous, `s3rver` should expect both versions of `x-amz-copy-source`. This change adds a '/' to `copy` in case `x-amz-copy-source` does not have a leading '/'.
For S3's documentation, see https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html
> Normalize x-amz-copy-source

- bin/s3rver.js
Two things: the index document option was misspelt, and both that option and the error document one were returning booleans rather than paths, despite the requirements of controllers.js. I've changed both, and everything seems to be working as it should be.
> Options not working

- README.md
- lib/app.js
- lib/controllers.js
- lib/file-store.js
- lib/models/s3-object.js
- lib/utils.js
Sorry these commits are a bit all over the place, there were just a few features I needed immediately and didn't organize them into separate branches for separate pull requests. Let me though if this is problematic.
I'll just outline in a bit more detail exactly what these do:
1. Instead of returning an `app` object with just the custom serve method, I extended the express app with the serve method and returned the express app. This allows s3rver to run on the same port as an existing web server when using express's app mounting feature.
2. There was a bug that prevented using prefix matching and possibly some other path-related functions on Windows since the `fs` module adapts to the OS when creating path strings. I just used `url.format()` to essentially replace `\\` with `/` in the …
> Support setting the ContentDisposition parameter, other general improvements

- lib/file-store.js
This was probably introduced in eeb5793 after I changed `fs` calls to use streams. On Windows, Node.js still has a filesystem lock on new files and attempting to delete (and likely overwrite) them will result in
```
EPERM: operation not permitted, stat 'c:\...'
```
until the offending process is restarted.
I think I know where to look to fix it, I should have time tomorrow to attach a pull request if this isn't resolved by then.
> Files likely not closed after writing

- lib/controllers.js
- test/test.js
The regex was wrong. In order to support domain-style buckets with
subdomains, `.` must be allowed. This now better matches the S3 docs.
> Support domain-style bucket names.

- lib/logger.js
Add a log label to create a clear delineation between S3rver logs and an users application.  This is particularly useful when using S3rver programmatically within an application (e.g. during development or testing time).
> Add Log Label

- lib/file-store.js
This aligns with the s3 api when createBucket is called.
(e.g., `createBucket({ Bucket: "path/to/bucket"  } ...`)
> Changed mkdir to mkdirp to ensure recursive directory creation

- lib/controllers.js
- lib/file-store.js
- lib/xml-template-builder.js
- test/test.js
Hi, thanks a lot for S3rver!
Our S3-based application uses object copying with metadata replacement, and we realized that it's not supported by S3rver. I just added the missing support. The relevant S3 operation is [PUT Object - Copy](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html), in particular, the `x-amz-metadata-directive` header.
> Add support for copying objects with metadata replace

- lib/controllers.js
- test/test.js
If the object specified in the request is not found, `s3rver` responds with 404 error, unlike Amazon S3 that returns the result as deleted for both [single](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html) and [multi-object](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html) operations.
Align `deleteObject` and `deleteObjects` with the API spec and return a success response even when the target object does not exist.
> Do not fail when deleting a nonexistent object

- lib/app.js
- lib/controllers.js
- lib/file-store.js
- lib/xml-template-builder.js
- test/test.js
Resolves #33 
Multipart uploads is a major feature missing from this mock S3 server. Without it, it's impossible to test uploading files larger than 5MB using `aws-sdk`:
```javascript
const s3 = new AWS.S3()
// ...
s3.upload(params, (err, data) => {})
```
> Add support for multipart uploads

- bin/s3rver.js
- lib/index.js
- test/test.js
The `S3rver` class already accepts `key` and `cert` options for running with TLS. This PR exposes those options through the CLI.
Running with TLS is useful in conjunction with #49: we can supply a self-signed certificate for *.amazonaws.com, and then have s3rver handle requests intended for https://[bucket].s3.amazonaws.com, the default endpoint used by AWS SDKs.
> Expose TLS options through CLI

- lib/app.js
- test/test.js
I have a situation where I'm testing S3 interaction code as a black box. I can't (or prefer not to) modify the code to point to a special S3 endpoint and force path-style requests. Instead, what I'd like to do is intercept traffic bound for `[bucket].s3.amazonaws.com` and redirect that traffic to s3rver, e.g. with a rule in /etc/hosts.
This PR has s3rver parse the `host` header and, if it matches a [bucket vhost](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro), then it handles the request for that bucket.
This only changes the behavior when s3rver receives a request with a host like `[bucket].s3(-[region])?.amazonaws.com`, so normal usage stays the same.
> Respond to requests on bucket vhost

- test/test.js
Currently the tests affect each other.
IMHO a test should be self contained.
Since the tests take some time, it can be really painful to debug a single test when they all affect each other.
@leontastic Are you okay with me using the promise instead of the callback api of the aws-sdk?
**TODO**
> Make tests independent

- lib/index.js
- lib/utils.js
- test/test.js
- Adds failing tests for new option `removeBucketsOnClose` (defaults to false).
When the option is set to true all buckets will be deleted when calling `server.close`.
closes #58
> Cleanup Option

- lib/file-store.js
This resolves a subtle non-deterministic bug caused by attempting to access saved upload data in order to create metadata immediately after.
In my integration tests uploading thousands of files, I would sometimes get an `ENOENT` on the `fs.stat` call in `createMetaData` function in `lib/file-store.js`.
It appears we're listening on the generic `finish` stream event before calling `createMetaData`, where we really should be listening on the [`close` event](https://nodejs.org/api/fs.html#fs_event_close_1) which is emitted after the underlying file descriptor is closed (therefore guaranteeing the file exists when `fs.stat` is being called in `createMetaData`). It appears listening on the `finish` event does not provide this guarantee, while it will work most of the time.
> wait for writeStream file descriptor to close before calling fs.stat

- README.md
- bin/s3rver.js
- lib/app.js
- lib/controllers.js
- lib/cors.js
- lib/index.js
- package.json
- test/resources/cors_sample_policy.xml
- test/resources/cors_test1.xml
- test/test.js
(Close #59 if you decide to merge this as this tracks off those changes)
This uses Express's `cors` package to support customizing what headers the S3 server exposes/allows. It shouldn't affect existing configurations as the `--cors` option doubles as a boolean to enable the basic CORS config and as a file path to a full XML configuration.
> Support for S3 CORS configuration policies

- lib/file-store.js
- test/test.js
Previously, all common prefixes were returned when using both `Delimiter` and `Prefix`, but s3 only provides the shortest. For example, I created this hierarchy (taken from the tests) in S3:
```
const paths = [
'folder1/file1.txt',
'folder1/file2.txt',
'folder1/folder2/file3.txt',
'folder1/folder2/file4.txt',
'folder1/folder2/file5.txt',
'folder1/folder2/file6.txt',
'folder1/folder4/file7.txt',
'folder1/folder4/file8.txt',
'folder1/folder4/folder5/file9.txt',
'folder1/folder3/file10.tx',
];
```
When running `listObjects()` with `{Delimiter: '/', Prefix: 'folder1/'}`, I get:
```
{
...
Contents: 
[ { Key: 'folder1/file1.txt', ... },
{ Key: 'folder1/file2.txt', ... } ],
Prefix: 'folder1/',
Delimiter: '/',
CommonPrefixes: 
[ { Prefix: 'folder1/folder2/' },
{ Prefix: 'folder1/folder3/' },
{ …
```
> Find only short common prefixes when using Delimiter and Prefix

- .npmrc
With npm 5, I have to run `npm update --no-save` or delete my local `package-lock.json` to keep dependencies up to date without making changes that interfere with the renovate bot. `package-lock` only really makes sense for apps whereas we're only concerned about we put on npm.
> Don't generate package-lock.json

- lib/file-store.js
- lib/xml-template-builder.js
- test/test.js
I've actually encountered this and worked around it thinking it was just some annoying behavior for S3, but it's actually just been implemented wrong here. Ideally this would have been caught a long time ago since it's basically the result of a syntax error, but `var` is just the best at hiding those -_-.
I'm still working on rebasing the fs store refactor I've had for a while now that has a much better implementation of this with proper error handling, but I'll add this now just since there's some value in giving new test cases their own PR.
> Fix copyObject operations with "COPY" MetadataDirective

- lib/cors.js
- test/test.js
I accidentally treated the result of `req.get()` as an array and didn't split it by commas. I've added test cases for `OPTIONS` requests and adjusted the implementation accordingly.
> Fix OPTIONS requests when Access-Control-Request-Headers header is present

- lib/cors.js
- test/test.js
Another minor mistake I didn't catch as I was trying to tidy up this feature. Originally I had `matchedRule`
in a different spot where it `CORSConfiguration` was assumed to be defined but it got moved around when I implemented `OPTIONS` request handling.
> Fix CORS middleware when no config is specified

- bin/s3rver.js
- lib/app.js
- lib/controllers.js
- lib/file-store.js
- lib/index.js
- lib/models/bucket.js
- lib/models/s3-event.js
- lib/models/s3-object.js
- lib/utils.js
- lib/xml-template-builder.js
- test/test.js
- Use classes where applicable
- Use arrow functions for callbacks
- Use object initializer shorthands
- Swap lodash functions with native implementations where possible
- Alphabetically order imported modules
I avoided making everything use Promises since I'd rather jump straight to async/await style when we eventually decide to do that.
This shouldn't change any existing behavior at all, it should all be purely syntax updates.
> Use modern ES features where applicable

- lib/index.js
- test/test.js
When the user passes `port : 0`, the operating system will dynamically allocate an available port for us, which we then return to the user so that they know how to connect to us.
Fixes #162
> Support running on port 0

- test/test.js
Closes #154. I had to use `request` instead of an `AWS.S3` client since it always forces the `application/octet-stream` content type if none is specified.
> Test objects stored with no content type

- lib/xml-template-builder.js
> Correctly format date

- lib/xml-template-builder.js
- test/test.js
I never added any tests checking that the value for IsTruncated actually made it into the response. I modified a couple relevant tests to check the flag after fixing the XML response.
> Include correct IsTruncated value in listObjects response

- lib/controllers.js
- test/test.js
To match how S3 copyObject works, this changes s3rver to URI-decode the value passed in the `x-amz-copy-source` header.
[S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys) say UTF-8 is supported and [copyObject reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) says "CopySource — (String) The name of the source bucket and key name of the source object, separated by a slash (/). *Must be URL-encoded.*"
p.s. s3rver is awesome, thank you for making it!
> Decode x-amz-copy-source to support spaces & special characters

- lib/app.js
- package.json
- test/test.js
This adds compatibility with RxJS 6 for when we decide it's appropriate to update, for now we require RxJS 5.5 to avoid breaking changes. This also addresses the insecure dependency warnings on David.
> Use RxJS pipeable operators

- lib/index.js
This fixes the close() callback not being optional. I was debating if it was a bad idea to make resetFs() sync, but considering unlinking is a pretty cheap file system operation, I think the only scenarios that would see any impact are testing suites that have many s3rver instances running concurrently while serving many files that need cleaned up?
> Avoid monkeypatching the close method on the returned server instance

- lib/models/s3-event.js
- lib/models/s3-object.js
- test/test.js
It should not rely on the object's creation date, especially since that value never exists in S3rver.
> S3Event's eventTime should always be a new date

- bin/s3rver.js
Self-explanatory title. For me exiting with a status of zero is problematic when configuring S3rver for use as a background task in VSCode.
> CLI: Exit with non-zero status with misconfigured data directory

- lib/cors.js
- test/test.js
This fixes issue #346 
So for whatever reason the client I am using, when making an `OPTIONS` request to `s3rver` is not specifying any `Access-Control-Request-Header` headers at all. As a result `s3rver` erroneously responds with a 403 error. S3 proper does not have this same issue for the exact same request.
I have added a test which fails with vanilla master code and passes once I made the corresponding fix.
The issue appears to be [here](https://github.com/jamhall/s3rver/blob/master/lib/cors.js#L90) where if the header is not specified then `requestHeaders` ends up being `[ '' ]` rather than `[]`. Then when we get to the check [here](https://github.com/jamhall/s3rver/blob/master/lib/cors.js#L100) the conditional expression `allowedHeaders.length < requestHeaders.length` fails because …
> Handle the case where the access-control-request-header is not provided

- lib/controllers.js
- lib/stores/filesystem.js
- package.json
- test/test.js
Range requests were doing a few things wrong:
1) always returning true regardless of whether or not the range was successful.  If the range is completely out of bounds a 416 must be returned
2) returning the requested range as the size and not the actual amount of data returned
This broke things that depend on range requests (notably s3-blob-store & feathers-blob) which we use extensively.  Hoping for a quick merge & tag so we can keep pulling from the real upstream.  
Thanks for a great project!
> Fix range handling for oversized and out of range situations

- lib/controllers.js
- lib/models/s3-object.js
- lib/stores/filesystem.js
- package.json
- test/test.js
This ensures no file handles are left open after receiving an unsatisfiable range request by never opening the stream in the first place.
Also I found that on my end, the value reported  by `fs.ReadStream#byteRead` was often 0 bytes since I'm guessing that value only reflects what has been lazily read.
> reimplement #373 to work on Windows

- lib/cors.js
- test/resources/cors_invalid1.xml
- test/resources/cors_invalid2.xml
- test/resources/cors_invalid3.xml
- test/test.js
The CORS middleware already does some rudimentary validation, this extends it to cover cases like #383 and adds tests.
> Additional CORS validation

- lib/stores/filesystem.js
- lib/utils.js
- test/test.js
Resolves #375. The old implementation didn't check if the directory was empty after running the function on its children.
> Fix empty directory cleanup when deleting a deeply nested key

- README.md
- lib/middleware/authentication.js
- lib/middleware/response-header-override.js
- lib/middleware/website.js
- lib/models/error.js
- lib/s3rver.js
- lib/utils.js
- test/test.js
This includes full support for signature version 2 and partial support for version 4. This also supports specifing `x-amz-meta-*` headers via query parameters and overriding response headers via `response-*` query parameters.
The test suite is by no means comprehensive but should cover the most important errors typically encountered. There are a lot of edge cases that I've done my best to handle as accurately as possible.
Here's the list of the features currently not implemented in the signature version 4 implementation:
* Verification of a provided signature (and calculating signing keys)
* Verification of content hash for signed payloads
* Validation of each component of an Authorization header
* Well-formedness check of Credential, SignedHeaders, and Signature parameters
* Validation …
> Support verification of signed requests and other special presigned request behavior

- lib/stores/filesystem.js
- test/test.js
This addresses #390 by escaping reserved characters URL-style. For example, `<identity:key>` becomes `&3cidentity&3akey&3e` .
> Escape invalid path characters in win32 envs

- lib/middleware/vhost.js
- test/test.js
(for example docker environment), now we don't only test for ctx.hostname being 127.0.0.1, but any ip
other when using docker, you would end up with an ip in for example 172.12.0.6, and vhost.js would
have erroneously replaced ctx.path by  `/undefined/$bucketname`
> handle s3rver launched with ip other than localhost

- lib/controllers/bucket.js
- lib/routes.js
The route handlers weren't using the S3Error model used to format error responses for 501 errors. This also adds `location` to the list of bucket methods to fix #439.
> Report NotImplemented for stubbed routes

- .travis.yml
- lib/s3rver.js
Make compatible with node < 8.15.0
`http.createServer` does not accept a serverOptions object in node.js < 8.15.0, so pass undefined.
When https or node >= 8.15 pass serverOptions into createServer.
Use semver to determine the version of Node.js that is running.
This fixes an error when running in Node 8.10.0 (the version AWS lambda currently uses).
```
TypeError: "listener" argument must be a function
at new Server (_http_server.js:269:10)
at Object.createServer (http.js:34:10)
at S3rver.listen (lib/s3rver.js:148:8)
at runAsync (lib/s3rver.js:130:36)
```
> Make http compatible with Node.js < 8.15.0, fix TypeError: "listener" argument must be a function

- lib/controllers/bucket.js
- lib/controllers/object.js
- lib/controllers/service.js
- lib/middleware/authentication.js
- lib/middleware/response-header-override.js
- lib/models/account.js
- lib/models/config.js
- lib/models/error.js
- lib/models/event.js
- lib/s3rver.js
- lib/stores/filesystem.js
- lib/utils.js
- package.json
- test/test.js
Resolves #110. This implements "starts-after" for GET Bucket v2 as well all pagination-related response data for both the v1 and v2 APIs. This also fixes the behavior for "marker"/"starts-after" (they erroneously require a key starting with the marker to exist in order to work properly).
I also ended up doing some significant refactoring to the tests around listObjects since they weren't very strict and also ran very slowly (it actually isn't necessary to generate 1000+ objects to make adequate test cases most of the time).
> Fully implement List Objects V2 with pagination response elements

- lib/stores/filesystem.js
- test/test.js
Hello! This issue came up while trying to copy objects.
I think there's an issue with the `getMetadata` function overwriting the object file instead of the md5 file. Adding the md5 extension as in this PR seemed to do the trick.
Please let me know if I can provide any more info! Thank you!
> Add md5 extension to md5 file

- lib/middleware/website.js
- lib/models/config.js
- lib/models/routing-rule.js
- test/resources/website_test1.xml
- test/resources/website_test2.xml
- test/test.js
Hey, I need support for routing rules for my setup so I figured I'd give it a shot at implementing them. This is a work in progress, but I figured I'd open the PR early.
The example I have implemented so far is what I personally need, but it isn't the simplest scenario. I wanted to prove out that I could get this working for my case before implementing anything else. I only have one test at the moment, but I'll expand them as I go.
Any feedback is welcome. I'll update this PR as I progress.
> Website Routing Rules

- lib/stores/filesystem.js
- test/test.js
Closes #484. This was a very subtle bug, caused by the fact that the last byte of an empty object "begins" at offset -1. This can be worked around by just ensuring the last byte is nonnegative.
> Fix calling HEAD on an empty object

- README.md
- bin/s3rver.js
- lib/controllers/bucket.js
- lib/middleware/vhost.js
- lib/middleware/website.js
- lib/s3rver.js
- test/test.js
Resolves #487. This is for advanced use-cases where the entire S3 service endpoint is self-hosted with a real domain name. By default, S3rver will assume a default service endpoint of `amazonaws.com`, and it can be overridden by declaring `serviceEndpoint: 'my-domain.com'` in S3rver's class constructor.
This PR also consolidates all hostname parsing to vhost.js so that any middleware that alters its behavior based on the format of the hostname can refer to `ctx.state.vhost` and `ctx.state.service` and avoid parsing the hostname again.
> Support declaring custom service endpoint

- lib/s3rver.js
The JSDoc on `close` claims that it returns` this` when called with a callback, but in practice, it was only returning `this` if the server wasn't running.
> Consistently return `this` from close

- lib/stores/filesystem.js
It allows use NodeJS backpressure: https://nodejs.org/es/docs/guides/backpressuring-in-streams/
In this way we will take out the return value of the .write() function.
> Use transform & pipe to manage streams

- lib/middleware/authentication.js
- lib/routes.js
- lib/utils.js
- test/controllers/object.spec.js
- test/helpers.js
Originally I was under the impression that our test suite ran using v2 signatures for all requests, but they're actually defaulting to v4 signatures (and S3rver makes no attempt to verify those). Turning on v2 signatures makes a whopping 101/184 tests fail!
This PR fixes all v2 verification errors within the testing suite and resolves #513 (closes #526).
> Fix v2 signature verification

- lib/controllers/object.js
- test/controllers/object.spec.js
Closes #629. This fixes requests where the ETag for each part is sent without surrounding double quotes.
> Use looser ETag parsing in Complete Multipart Upload requests

- bin/s3rver.js
- lib/middleware/vhost.js
- lib/s3rver.js
- test/middleware/vhost.spec.js
Resolves #557 (closes #558). This adds `vhostBuckets` to the constructor options and a `--no-vhost-buckets` option to the CLI. This also prevents the OS or container's own hostname from being interpreted as a bucket name regardless of the setting. Virtual host style access is still enabled by default with these changes.
> Support disabling vhost-style bucket access

- lib/stores/filesystem.js
- test/controllers/object.spec.js
This fixes the Windows test suite finally. Surprisingly, it only took a single line change!
> fix: properly close write stream when object content is a buffer

- lib/middleware/website.js
- test/fixtures/website-test2.xml
- test/middleware/website.spec.js
Supersedes #574
The fix was essentially just to check if an index document exists at the current key. The diff ended up being noisier than I anticipated since the behavior extends to keys with or without a trailing slash.
> fix: support SPA routing to root index page

- lib/middleware/authentication.js
- test/helpers.js
- test/middleware/authentication.spec.js
- test/middleware/website.spec.js
- Implement v4 signing algorithm, minor code changes necessary to extract relevant data from the request
- Fixed failing CORS OPTIONS request when using signed headers (I think OPTIONS should not be verified at all, since it's a different HTTP method so would definitely result in a different signature).
- Resolved small issue when calculating the canonical query string regarding params with no value (v2 does not require the = to be present, v4 does), so I moved that stripping code into the v2-specific code path
- Added unit tests for incorrect v4 signatures when using headers as well as using query params
- Confirmed locally that signed GET and PUT requests work correctly, including CORS, from my web app
- Confirmed locally that corrupting a signed URL results in a 403
Fixes #659
> Implement support for signature v4

- lib/controllers/object.js
- lib/routes.js
- lib/stores/filesystem.js
- test/controllers/object.spec.js
This partially implements [Upload Part - Copy](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html):
This is as much as I personally need from this function.
> Add Upload Part - Copy

- lib/models/object.js
- test/controllers/object.spec.js
Fixes #727. No additional validation is performed beyond checking that the provided storage class value is allowed.
> feat(object): add basic support for storage classes

- lib/stores/filesystem.js
- lib/utils.js
- test/controllers/object.spec.js
Fixes errors when trying to re-create directories that already exist.
Uses a helper function to verify for the directory existence first.
Note this PR also includes the fix for `options.start !== undefined` as I've built on top of my previous branch.
> fix(object): Takes into account the range of bytes starting with 0

- README.md
The field is `address` in the code, not `hostname`. Setting `hostname` has no effect.
See: https://github.com/jamhall/s3rver/blob/main/lib/s3rver.js#L146
> docs: option address, not hostname

- .github/workflows/ci.yml
- package-lock.json
Node 16 will be entering active LTS in a few weeks and is the first even-numbered release to include npm 7. This PR regenerates package-lock to lockfile version 2 which is backwards compatible with all npm versions currently used in CI.
> chore: upgrade CI to npm 7, fix npm audit report
